Repository priyanshu-kr/priyanshu-kr.github.io, pull requests merged in 2022-10, with the labels that each got.

#2 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#3 Updated photo and colours
  css/style.css
  images/my_bg18_1.jpg
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#4 Updated_hover_colors
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#5 Updated_enhacements
  css/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
